### PR TITLE
Add yaml-lint check step on ci

### PR DESCRIPTION
**Pull request by denis-tingaikin**
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>

## Motivation

This PR:

1. adds check for YAML files: https://github.com/adrienverge/yamllint
2. fixes found issues by yamllint.

### CODE REVIEW

**Comment by z2sx** [comment]
Do we have yaml files in the project? :) //cc @haiodo Anyway Denis, please make linter happy :)

**Comment by z2sx** [comment]
OK, we have some in the `documentation` framework. Looks like it would be hard to make linter happy :)

**Comment by denis-tingaikin** [comment]
@z2sx Done.

**Comment by denis-tingaikin** [comment]
> OK, we have some in the documentation

It is also helpful for checking ci files :) 

For example, .github/workflows/build.yml

**Comment by z2sx** [comment]
Cool! Please add yourself to AUTHORS file, this is for license / contribution tracking :)

**Pull request merged**
